# GitHub Pages configuration for FinansimPro
title: FinansimPro Email Verification
description: Email verification page for FinansimPro app
baseurl: "/finansimpro"
url: "https://kelsier1425.github.io"